api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "car-fitment-product"
uid = "a588ae28-c944-ba77-2c85-6047ed8403b5d42c2c01"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Action.jsx"
target = "admin.product-details.action.render"

[extensions.capabilities]
api_access = true
network_access = true
