api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "car-fitment-bulk"
uid = "4130cb4c-2d0b-cde5-d1de-06c064360c720b8d414e"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Action.jsx"
target = "admin.product-index.selection-action.render"

[extensions.capabilities]
api_access = true
network_access = true
