api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "car-fitment-index"
uid = "9ff4b93f-9764-80f5-5645-648f40c0968790d16581"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Action.jsx"
target = "admin.product-index.action.render"

[extensions.capabilities]
api_access = true
network_access = true
