-- Fitment table: source of truth for product ↔ vehicle compatibility
-- Apply in Supabase SQL editor or via supabase CLI migrations.

create table if not exists public.fitment (
  id bigint generated by default as identity primary key,

  shop_domain text not null,

  product_gid text,
  product_handle text,
  sku text,
  article_number text,
  brand text,

  vehicle_gid text,
  vehicle_handle text,
  vehicle_key text not null,
  vehicle_display_name text,

  category_key text,
  system_group_key text,
  subcategory_key text,

  source text not null default 'import',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Prevent accidental duplicates for the same shop+product+vehicle+subcategory.
create unique index if not exists fitment_unique_shop_product_vehicle_subcategory
  on public.fitment (shop_domain, product_gid, product_handle, vehicle_key, subcategory_key);

-- Requested indexes for read patterns.
create index if not exists fitment_shop_vehicle_key
  on public.fitment (shop_domain, vehicle_key);

create index if not exists fitment_shop_product_handle
  on public.fitment (shop_domain, product_handle);

create index if not exists fitment_shop_vehicle_subcategory
  on public.fitment (shop_domain, vehicle_key, subcategory_key);

-- Optional but recommended: keep updated_at current.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists fitment_set_updated_at on public.fitment;
create trigger fitment_set_updated_at
before update on public.fitment
for each row
execute function public.set_updated_at();

-- Enable RLS by default; backend should use service role key.
alter table public.fitment enable row level security;

